<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Pilih cara mengonfirmasi bahwa ini Anda</name>
   <tag></tag>
   <elementGuidId>48a6103f-c363-4491-9217-8dd5e0a67610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[@id='u_0_4_/k']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>949e25d2-f594-4e2e-bf54-d09cf7ed30a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_4_/k</value>
      <webElementGuid>b0d10bce-017b-4649-9f9d-cfde360ed4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih cara mengonfirmasi bahwa ini Anda</value>
      <webElementGuid>ca1bbfe7-a52b-4476-b96c-ae8bbf9d8217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_4_/k&quot;)</value>
      <webElementGuid>cb43ffe8-ecd2-425e-8f97-376aee7ce9d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='u_0_4_/k']</value>
      <webElementGuid>57458f50-9e08-4f30-8756-0ffce4249419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_3_bg']/strong</value>
      <webElementGuid>0bd0495f-5f56-4a26-a999-9e2c335b8aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>783f8883-f28e-4aa5-8598-ad47f4c78916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'u_0_4_/k' and (text() = 'Pilih cara mengonfirmasi bahwa ini Anda' or . = 'Pilih cara mengonfirmasi bahwa ini Anda')]</value>
      <webElementGuid>4985d0e9-f272-4f43-8372-7342c034c5cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
